[package]
name = "wizard-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
wizard-state = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
rfd = { workspace = true }
wizard-media = { workspace = true }
image = { workspace = true }
